### ISSUE TITLE
VmbFeatureList

### ISSUE THREAD

**Issue by Blueicaro** [mattiwalter/Delphi-Allied-Vision-Grab#1]
Hello, I trying to use VmbFeatureList function. But I couldn't. I got errors, or I got nothing
Can you provide a example?
Thanks

**Comment by Blueicaro** [comment]
Hi, I found the solution by my self.
program project1;

{$mode objfpc}{$H+}

uses {$IFDEF UNIX} {$IFDEF UseCThreads}
  cthreads, {$ENDIF} {$ENDIF}
  Classes,
  VimbaC,
  VmbCommonTypes;

var
  Status: VmbError_t;
  AlliedCamera: VmbHandle_t;
  total, feo: VmbUint32_t;
  lista: VmbFeatureInfo_t;
  P: pVmbFeatureInfo_t;
  c: PAnsiChar;
  I: Integer;
begin
  Status := VmbStartup();
  if Status <> Ord(VmbErrorSuccess) then
    Halt(Status);

  Status := VmbCameraOpen(PChar('192.168.1.169'), 1, @AlliedCamera);

  P := @Lista;
  P := nil;
  total:=0;
  status := VmbFeaturesList(AlliedCamera, p, 0, total, SizeOf(Lista));

  if status = 0 then
  begin
    p := @Lista;
    Getmem(p,(Sizeof(Lista)*Total));
    Status := VmbFeaturesList(AlliedCamera, (p), (SizeOf(Lista) * Total), feo, SizeOf(Lista));

  end;
  For I := 0 To Feo-1 do
  begin
    c := p[i].name;
    Writeln(c);
  end;
  status := VmbCameraClose(AlliedCamera);
  VmbShutdown;
  Freemem(P);

end.

**Comment by nplower** [comment]
Hello,

Thank you so much for posting this.
I am having the same trouble.
From your post, I seem to be having trouble with type pVmbFeatureInfo_t.
I can define P as :  P: ^VmbFeatureInfo_t; 
However, the function is looking for type VmbFeatureInfo_t, and errors when it sees a pointer of type VmbFeatureInfo_t.
Any thoughts?
